### ISSUE TITLE
Errors if a guild doesn't have the specified rank

### ISSUE THREAD

**Issue by 2kai2kai2** [2kai2kai2/eu4img#9]
`2019-12-16T03:32:59.893019+00:00 app[worker.1]: Ignoring exception in on_message`
`2019-12-16T03:33:00.002903+00:00 app[worker.1]: Traceback (most recent call last):`
`2019-12-16T03:33:00.005012+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 270, in _run_event`
`2019-12-16T03:33:00.005016+00:00 app[worker.1]:     await coro(*args, **kwargs)`
`2019-12-16T03:33:00.005023+00:00 app[worker.1]:   File "EU4Bot.py", line 944, in on_message`
`2019-12-16T03:33:00.005025+00:00 app[worker.1]:     elif (text.upper() == prefix + "NEW") and checkResAdmin(message.guild, message.author):`
`2019-12-16T03:33:00.005027+00:00 app[worker.1]:   File "EU4Bot.py", line 97, in checkResAdmin`
`2019-12-16T03:33:00.005030+00:00 app[worker.1]:     return getRoleFromStr(s, os.getenv("MIN_ADMIN")) <= u.top_role`
`2019-12-16T03:33:00.005098+00:00 app[worker.1]: TypeError: '<=' not supported between instances of 'NoneType' and 'Role'`

**Comment by 2kai2kai2** [comment]
Should not grant perms if the perm doesn't exist, or just default to the highest rank.

**Comment by 2kai2kai2** [comment]
Always give top rank perms
